using System.Globalization;
using Galbox.Data.Entities;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Galbox.Data.Migrations;

/// <summary>
/// One column of the baseline schema.
/// </summary>
public sealed class BaselineColumn
{
    /// <summary>Column name.</summary>
    public string Name { get; init; } = string.Empty;

    /// <summary>Declared storage type as EF Core generates it (TEXT / INTEGER / REAL / BLOB).</summary>
    public string StoreType { get; init; } = "TEXT";

    /// <summary>True when the column is NOT NULL.</summary>
    public bool IsNotNull { get; init; }

    /// <summary>Default value expression as generated by EF Core, or null.</summary>
    public string? DefaultValueSql { get; init; }
}

/// <summary>
/// One table of the baseline schema, including the exact DDL EF Core produced for it.
/// </summary>
public sealed class BaselineTable
{
    /// <summary>Table name.</summary>
    public string Name { get; init; } = string.Empty;

    /// <summary>The <c>CREATE TABLE</c> statement EF Core generated for this table.</summary>
    public string CreateSql { get; init; } = string.Empty;

    /// <summary>Columns of the table, in the order EF Core created them.</summary>
    public List<BaselineColumn> Columns { get; init; } = new();

    /// <summary>Index creation statements belonging to this table.</summary>
    public List<(string Name, string Sql)> Indexes { get; init; } = new();
}

/// <summary>
/// The structure the baseline migration produces, captured by actually running that migration against a
/// throw-away database.
/// </summary>
/// <remarks>
/// <para>
/// This is what makes the legacy repair safe: the repair only ever adds objects that the <i>baseline</i>
/// declares. It must never add columns that belong to a later migration (for example <c>Games.Status</c>), because
/// those migrations are still pending and would then fail with <c>duplicate column name</c> — the exact defect
/// that made the first version of this repair unusable.
/// </para>
/// <para>
/// Deriving the expectation from the baseline migration (instead of from the live EF model) keeps the repair
/// correct as the model evolves: only the baseline is frozen, and it is frozen by design.
/// </para>
/// </remarks>
public sealed class BaselineSchema
{
    /// <summary>Baseline tables indexed by name.</summary>
    public Dictionary<string, BaselineTable> Tables { get; } = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>
    /// Builds the baseline schema by applying only <paramref name="baselineMigrationId"/> to a temporary database
    /// and reading back what it created.
    /// </summary>
    /// <param name="context">A context used to reach the migration infrastructure (its database is not touched).</param>
    /// <param name="baselineMigrationId">Identifier of the baseline migration.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The baseline structure.</returns>
    public static async Task<BaselineSchema> CaptureAsync(
        GalboxDbContext context,
        string baselineMigrationId,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(context);

        var scratchPath = Path.Combine(
            Path.GetTempPath(),
            "galbox-baseline-" + Guid.NewGuid().ToString("N") + ".db");

        try
        {
            var options = new DbContextOptionsBuilder<GalboxDbContext>()
                .UseSqlite($"Data Source={scratchPath}")
                .Options;

            await using (var scratch = new GalboxDbContext(options))
            {
                await scratch.GetService<IMigrator>()
                    .MigrateAsync(baselineMigrationId, cancellationToken)
                    .ConfigureAwait(false);
            }

            return Read(scratchPath);
        }
        finally
        {
            DeleteQuietly(scratchPath);
            DeleteQuietly(scratchPath + "-wal");
            DeleteQuietly(scratchPath + "-shm");
        }
    }

    /// <summary>
    /// Reads the structure and DDL of every table in a database file.
    /// </summary>
    /// <param name="databasePath">Path of an existing database.</param>
    /// <returns>The structure of the database.</returns>
    public static BaselineSchema Read(string databasePath)
    {
        var schema = new BaselineSchema();

        using var connection = new SqliteConnection($"Data Source={databasePath};Mode=ReadOnly");
        connection.Open();

        // Tables + their CREATE TABLE statements.
        using (var command = connection.CreateCommand())
        {
            command.CommandText =
                "SELECT name, IFNULL(sql, '') FROM sqlite_master " +
                "WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name;";

            using var reader = command.ExecuteReader();
            while (reader.Read())
            {
                var name = reader.GetString(0);

                // EF's own bookkeeping table is not part of the schema EnsureCreated() produced and is created by
                // EF itself when a migration is recorded; the repair must not be responsible for it.
                if (string.Equals(name, GalboxDatabaseInitializer.MigrationsHistoryTable, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                var table = new BaselineTable
                {
                    Name = name,
                    CreateSql = reader.GetString(1),
                    Columns = ReadColumns(connection, name)
                };

                schema.Tables[name] = table;
            }
        }

        // Indexes, attached to their table.
        using (var command = connection.CreateCommand())
        {
            command.CommandText =
                "SELECT name, IFNULL(sql, ''), tbl_name FROM sqlite_master " +
                "WHERE type = 'index' AND sql IS NOT NULL AND name NOT LIKE 'sqlite_%';";

            using var reader = command.ExecuteReader();
            while (reader.Read())
            {
                var indexName = reader.GetString(0);
                var sql = reader.GetString(1);
                var tableName = reader.GetString(2);

                if (schema.Tables.TryGetValue(tableName, out var table))
                {
                    table.Indexes.Add((indexName, sql));
                }
            }
        }

        return schema;
    }

    private static List<BaselineColumn> ReadColumns(SqliteConnection connection, string tableName)
    {
        var columns = new List<BaselineColumn>();

        using var command = connection.CreateCommand();
        command.CommandText = $"PRAGMA table_info(\"{tableName.Replace("\"", "\"\"")}\");";

        using var reader = command.ExecuteReader();
        while (reader.Read())
        {
            columns.Add(new BaselineColumn
            {
                Name = reader.GetString(1),
                StoreType = reader.IsDBNull(2) ? "TEXT" : reader.GetString(2),
                IsNotNull = reader.GetInt32(3) != 0,
                DefaultValueSql = reader.IsDBNull(4)
                    ? null
                    : Convert.ToString(reader.GetValue(4), CultureInfo.InvariantCulture)
            });
        }

        return columns;
    }

    private static void DeleteQuietly(string path)
    {
        try
        {
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }
        catch (IOException)
        {
            // A leftover temp file is harmless; SQLite cleans up its own scratch files on process exit.
        }
    }
}
