// <auto-generated />
using System;
using Galbox.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Galbox.Data.Migrations
{
    [DbContext(typeof(GalboxDbContext))]
    partial class GalboxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Galbox.Data.Entities.GameCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameCn")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameInfoId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Galbox.Data.Entities.GameDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewContent")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameInfoId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Galbox.Data.Entities.GameErrorRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SolutionInstructions")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SolutionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("GameInfoId");

                    b.HasIndex("IsResolved");

                    b.HasIndex("Severity");

                    b.ToTable("ErrorRecords");
                });

            modelBuilder.Entity("Galbox.Data.Entities.GameInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternativeExecutables")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundImagePath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Developer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EngineType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("InstallPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsScraped")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStatusUserSet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSessionTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("LaunchCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainExecutable")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameCn")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOriginal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("StatusChangedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalPlayTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedTime");

                    b.HasIndex("InstallPath");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("NameCn");

                    b.HasIndex("NameOriginal");

                    b.HasIndex("Status");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Galbox.Data.Entities.GameMediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameInfoId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("Galbox.Data.Entities.GameSaveBackup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSavePath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SaveNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameInfoId");

                    b.HasIndex("SaveNodeId");

                    b.ToTable("SaveBackups");
                });

            modelBuilder.Entity("Galbox.Data.Entities.GameScreenshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameInfoId");

                    b.ToTable("Screenshots");
                });

            modelBuilder.Entity("Galbox.Data.Entities.PatchRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadProgress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DownloadedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("InstalledTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatchType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameInfoId");

                    b.HasIndex("PatchType");

                    b.HasIndex("Status");

                    b.ToTable("Patches");
                });

            modelBuilder.Entity("Galbox.Data.Entities.SaveGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RouteName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameInfoId");

                    b.HasIndex("GameInfoId", "OrderIndex");

                    b.ToTable("SaveGroups");
                });

            modelBuilder.Entity("Galbox.Data.Entities.SaveNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CgTotalCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CgUnlockPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CgUnlockedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CgUnlockedIdsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChapterName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChapterProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtendedMetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParseError")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParseStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RouteName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SaveCreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SaveFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SaveFilePath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SaveGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SaveModifiedTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("SaveSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SceneLabel")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameInfoId");

                    b.HasIndex("IsSnapshot");

                    b.HasIndex("SaveGroupId");

                    b.HasIndex("SceneLabel");

                    b.HasIndex("GameInfoId", "SaveModifiedTime");

                    b.ToTable("SaveNodes");
                });

            modelBuilder.Entity("Galbox.Data.Entities.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoBackupOnExit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("AutoScanOnStartup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("AutoScrapeOnAdd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("AutoScreenshotOnExit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("BangumiAccessToken")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("BangumiAuthMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BangumiRefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BangumiTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BangumiUserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BangumiUsername")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("BossKeyModifiers")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("BossKeyVirtualKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultBackupPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultScrapingSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableAdvancedMonitoring")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableBangumi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnableBossKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnableCngal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnableVndb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnableYmgal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("GameDirectoriesJson")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<int>("JpgQuality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(90);

                    b.Property<int>("Language")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryViewMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchThresholdPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(90);

                    b.Property<bool>("MinimizeToTrayOnBossKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("MonitoringIntervalMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1000);

                    b.Property<int>("OnExitBehavior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnLaunchBehavior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScreenshotFormat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScreenshotPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowBossKeyNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("SourcePriorityJson")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCustomBackupPath")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("Galbox.Data.Entities.GameCharacter", b =>
                {
                    b.HasOne("Galbox.Data.Entities.GameInfo", "GameInfo")
                        .WithMany("Characters")
                        .HasForeignKey("GameInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInfo");
                });

            modelBuilder.Entity("Galbox.Data.Entities.GameDocument", b =>
                {
                    b.HasOne("Galbox.Data.Entities.GameInfo", "GameInfo")
                        .WithMany("Documents")
                        .HasForeignKey("GameInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInfo");
                });

            modelBuilder.Entity("Galbox.Data.Entities.GameErrorRecord", b =>
                {
                    b.HasOne("Galbox.Data.Entities.GameInfo", "GameInfo")
                        .WithMany()
                        .HasForeignKey("GameInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInfo");
                });

            modelBuilder.Entity("Galbox.Data.Entities.GameMediaFile", b =>
                {
                    b.HasOne("Galbox.Data.Entities.GameInfo", "GameInfo")
                        .WithMany("MediaFiles")
                        .HasForeignKey("GameInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInfo");
                });

            modelBuilder.Entity("Galbox.Data.Entities.GameSaveBackup", b =>
                {
                    b.HasOne("Galbox.Data.Entities.GameInfo", "GameInfo")
                        .WithMany("SaveBackups")
                        .HasForeignKey("GameInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Galbox.Data.Entities.SaveNode", "SaveNode")
                        .WithMany("Backups")
                        .HasForeignKey("SaveNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GameInfo");

                    b.Navigation("SaveNode");
                });

            modelBuilder.Entity("Galbox.Data.Entities.GameScreenshot", b =>
                {
                    b.HasOne("Galbox.Data.Entities.GameInfo", "GameInfo")
                        .WithMany("Screenshots")
                        .HasForeignKey("GameInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInfo");
                });

            modelBuilder.Entity("Galbox.Data.Entities.PatchRecord", b =>
                {
                    b.HasOne("Galbox.Data.Entities.GameInfo", "GameInfo")
                        .WithMany()
                        .HasForeignKey("GameInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInfo");
                });

            modelBuilder.Entity("Galbox.Data.Entities.SaveGroup", b =>
                {
                    b.HasOne("Galbox.Data.Entities.GameInfo", "GameInfo")
                        .WithMany("SaveGroups")
                        .HasForeignKey("GameInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInfo");
                });

            modelBuilder.Entity("Galbox.Data.Entities.SaveNode", b =>
                {
                    b.HasOne("Galbox.Data.Entities.GameInfo", "GameInfo")
                        .WithMany("SaveNodes")
                        .HasForeignKey("GameInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Galbox.Data.Entities.SaveGroup", "SaveGroup")
                        .WithMany("Nodes")
                        .HasForeignKey("SaveGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GameInfo");

                    b.Navigation("SaveGroup");
                });

            modelBuilder.Entity("Galbox.Data.Entities.GameInfo", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Documents");

                    b.Navigation("MediaFiles");

                    b.Navigation("SaveBackups");

                    b.Navigation("SaveGroups");

                    b.Navigation("SaveNodes");

                    b.Navigation("Screenshots");
                });

            modelBuilder.Entity("Galbox.Data.Entities.SaveGroup", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("Galbox.Data.Entities.SaveNode", b =>
                {
                    b.Navigation("Backups");
                });
#pragma warning restore 612, 618
        }
    }
}
