<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Galbox.MoyuVerifier</RootNamespace>
    <AssemblyName>Galbox.MoyuVerifier</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Galbox.Core\Galbox.Core.csproj" />
  </ItemGroup>
</Project>
