<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Galbox.Services</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Galbox.Core\Galbox.Core.csproj" />
    <ProjectReference Include="..\Galbox.Data\Galbox.Data.csproj" />
  </ItemGroup>

</Project>
